---
name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'     # matches every branch
      - '!main'  # excludes main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tflint:
    runs-on: ubuntu-latest
    name: tflint
    steps:
      - uses: actions/checkout@master

      - uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init tflint
        run: tflint --init

      - name: Run tflint
        run: tflint -f compact

  security:
    runs-on: ubuntu-latest
    name: snyk
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Vulnerability scan
        uses: snyk/actions/iac@master
        with:
          command: monitor
          args: --severity-threshold=low
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Snyk CLI
        run: npm install -g snyk
      - name: snyk monitor
        run: snyk iac test --report
        env:
          SNYK_TOKEN: ${{ secrets.ARC_SNYK_TOKEN }}
